### ISSUE TITLE
Query Params for Metrics Calls

### ISSUE THREAD

**Issue by jhunthrop** [newrelic/newrelic-client-go#292]
When providing `names` or `values` to a ReST metric endpoint, such as application metrics, only the last query parameter is respected.

example:
```
https://api.newrelic.com/v2/applications/<redacted>/metrics/data.json?names=GC%2FSystem%2FPauses&names=Supportability%2FNodejs%2FTransactions%2FSegments&values=as_percentage&values=average_time
```

This example will only return names = `Supportability/Nodejs/Transactions/Segments`, disregarding the first input of `GC/System/Pauses`.

New Relic ReST API doesn't treat multiple declarations of query parameters as an array. 

The only way that I've worked around this is to add the array brackets to the url encoding string on the params structs:

```
type MetricDataParams struct {
	Names     []string   `url:"names[],omitempty"`
	Values    []string   `url:"values[],omitempty"`
	From      *time.Time `url:"from,omitempty"`
	To        *time.Time `url:"to,omitempty"`
	Period    int        `url:"period,omitempty"`
	Summarize bool       `url:"summarize,omitempty"`
	Raw       bool       `url:"raw,omitempty"`
}
```

If this is needed, I don't mind to update and PR all of the parameters in the client that operate like this, just wanted to make sure that was the case.

**Comment by zlesnr** [comment]
Thanks for raising the issue.  I wasn't aware that you could use `url` tags like that, but just read up on it.  Pretty neat.

Sounds reasonable to me to update the structs for this.  Check the API docs for each struct, since the backing API for the various endpoints may not be as consistent as we might like them to be for the REST endpoints.  The nerdgraph APIs are really where we're trying to drive adoption, and our aim is to be a bit more consistent with graphQL moving forward.

Also, I'd request that we include integration tests to ensure that the services are responding like we think they should.  Perhaps some of the current tests will still operate correctly, but probably won't be testing for multiple values.  Let us know we can help any of that along, or if any of what is currently in place for tests doesn't make sense.  Thanks for volunteering!

**Comment by sanderblue** [comment]
Turns out we do this for [GetComponentMetricDataParams](https://github.com/newrelic/newrelic-client-go/blob/e24dc8fbddc5916793ab304da66f7336c500e812/pkg/plugins/components.go#L90-L93). At first glance this shouldn't be too much of an issue to update. I'll see what I can come up with. Thanks for reporting 🙂
