### ISSUE TITLE
Automate version increments for packages

### ISSUE THREAD

**Issue by jthurman42** [newrelic/newrelic-client-go#37]
### Objective
Updating package versions should be automated in some way so that we do not have to remember to update them.

### Acceptance Criteria
- Version updates to any package within `/pkg/*` are automated / required.
- Update to package version in `/pkg/*` automate / require change to `/newrelic/version.go`
- `/newrelic/version.go` is kept in sync with the git tag

### Related to
- #24

**Comment by zlesnr** [comment]
I was wondering about this one a bit, trying to figure out the use case of having the version file updated.  It looks like the binary we build contains eh LDFLAGS necessary to include the tag in the binary, so that we could just use that from reference.  Then the `version.go` would remain static at `0.0.1` or whatever forever, but maybe there is another use case for updating the version here in the code?  Forgive my ignorance here.

**Comment by jthurman42** [comment]
This is mostly managed with the release script now.
