### ISSUE TITLE
Question: Maturity and Official Support

### ISSUE THREAD

**Issue by skyzyx** [newrelic/newrelic-client-go#473]
We're experiencing a run-around with NR support because this project isn't the right _tier_ of open-source project. The specifics of the issue is not what this ticket is about:

(Using definitions from https://docs.newrelic.com/docs/licenses/license-information/general-usage-licenses/global-technical-support-offerings#h3-open-source-project-categories>)

* This is a _Community Project_, which means that support is provided here in GitHub (and _maybe_ NR Discuss), but that's it.

* As of this writing, the latest tag is `0.41.0`. There is no mention of _semantic versioning_ either in the README, nor in https://newrelic.github.io/developer-toolkit/.

My questions are these:

1. Is there a roadmap for achieving `1.0.0`? Are there criteria that can be shared/documented?

1. Do you intend to adopt semantic versioning as a software contract, and if so, which things are in/out-of-bounds? (e.g., versions of Go, versions of TLS, TLS ciphers, will they apply to the whole repo or by-package?)

1. The name of this project is "client", but many other vendors have "SDKs" (e.g., AWS). What is the difference between them (to you), and do you envision this project being more of one, or more of the other as it matures?

1. Are you able to discuss anything around the conditions under which this project would _graduate_ from a _Community Project_ to a _Community Plus Project_? (Which gains: “Support requests can be made through Github, Community, and Ticketed Support channels, depending on the service level associated with the New Relic account.”)

**Comment by zlesnr** [comment]
Hi @skyzyx, thanks for raising the issue.  Here is a rough take of where we're at today.

> Is there a roadmap for achieving 1.0.0? Are there criteria that can be shared/documented?

There is not currently a 1.x plan for this project.  We've avoided releasing a
1.x so that we may remain nimble in the case we want to shift the code patterns
that are in place here.  That said, the patterns in this project are
stabilizing.

We have ambitions of generating lots of code in this project, and that may put
some amount of pressure on the code to shift slightly, and so we are leaving
the door open for change.

We can discuss a 1.x as a team and see what the right course of action is.  Is
there a concern with the version being pre 1.x that you are able to share?

> Do you intend to adopt semantic versioning as a software contract, and if so, which things are in/out-of-bounds? (e.g., versions of Go, versions of TLS, TLS ciphers, will they apply to the whole repo or by-package?)

We currently adhere to semantic version for all of our releases and we
release the client as a single "atomic" release.  The version bumps reflect
change since the prior release.

With regard to TLS support, I would expect that services would constrain the
TLS support far more than this project.

I'm seeing posts like this, for example.

https://discuss.newrelic.com/t/january-tls-updates-apis-and-browser-apm/88869

For Go versions, probably v1.13+ is a reasonable constraint.
https://github.com/newrelic/newrelic-client-go/issues/474 to follow up.

> The name of this project is "client", but many other vendors have "SDKs" (e.g., AWS). What is the difference between them (to you), and do you envision this project being more of one, or more of the other as it matures?

This project is intended to interface with the majority of our public facing
APIs from code.  We also wanted to avoid confusion with some of the other New
Relic Projects, like the Go Agent.

An SDK in my mind would help developers write modules, or plugins, or some
other discrete and well-defined package.  An SDK might also include tools to
create a new project, lint a project, help developers conform to newer patterns
etc.

From that perspective, I think the term client here makes sense.  With this
project, we provide a collection of packages with methods that allow users to
operate the New Relic APIs.  What the end-user code looks like, or how it
behaves is entirely out of scope here from my perspective.

> Are you able to discuss anything around the conditions under which this project would graduate from a Community Project to a Community Plus Project? (Which gains: “Support requests can be made through Github, Community, and Ticketed Support channels, depending on the service level associated with the New Relic account.”)

It sounds like a matter of committing a small team to a customer SLA.  I don't
know what the future holds on this point.  Is there anything in particular
you're looking for here?

**Comment by skyzyx** [comment]
This is great, @zlesnr, and exactly what I was looking for. :)

> > Is there a roadmap for achieving 1.0.0? Are there criteria that can be shared/documented?
> 
> There is not currently a 1.x plan for this project. We've avoided releasing a
> 1.x so that we may remain nimble in the case we want to shift the code patterns
> that are in place here. That said, the patterns in this project are
> stabilizing.
> 
> We have ambitions of generating lots of code in this project, and that may put
> some amount of pressure on the code to shift slightly, and so we are leaving
> the door open for change.
> 
> We can discuss a 1.x as a team and see what the right course of action is. Is
> there a concern with the version being pre 1.x that you are able to share?

Only that, in terms of semantic versioning, pre-1.0.0 simply means that there is no discernible software contract in-place yet. This means that the code I write today may not work tomorrow (more or less). As you explain yourself, you do it "to remain nimble" which I understand as a developer, but the counter-argument is that the _nimbleness_ for you comes at the cost of _reliability_ for me.

On behalf of enterprise customers, I look forward to a stable and supported 1.0.0 release (meaning that I get to use my super-duper, ultra-platinum, really expensive support package for this project) where backwards-compatibility guarantees are a thing, and there are other bits of software contract that I can rely on.


> > Do you intend to adopt semantic versioning as a software contract, and if so, which things are in/out-of-bounds? (e.g., versions of Go, versions of TLS, TLS ciphers, will they apply to the whole repo or by-package?)
> 
> We currently adhere to semantic version for all of our releases and we
> release the client as a single "atomic" release. The version bumps reflect
> change since the prior release.
> 
> With regard to TLS support, I would expect that services would constrain the
> TLS support far more than this project.
> 
> I'm seeing posts like this, for example.
> 
> https://discuss.newrelic.com/t/january-tls-updates-apis-and-browser-apm/88869
> 
> For Go versions, probably v1.13+ is a reasonable constraint.
> #474 to follow up.

It's great to hear that the project views itself as being semantically-versioned… but that's not written down in any obvious places (e.g., README), and the reality is that most software project still have not adopted semver, so I (as a consumer) can't _assume_ such a thing.

But semantic versioning only addresses backwards-compatibility — and even then, only addresses the compatibility of some parts and not others. It's not a silver bullet. If, in the future, all New Relic endpoints suddenly expected TLS 1.3 or HTTP/3 or something else that doesn't impact function signatures, are they in-scope, or out of scope for the client API? Do you bump major version, minor version, or patch for such a change?

That's why I'm asking the follow-up questions. For all the things that semver covers, there are other things that it does not (and was not designed to) cover. If the answer is "I'm not quite sure yet", that's cool. But I think this is an example of something that needs deep thought before 1.0.0. 👍


> > The name of this project is "client", but many other vendors have "SDKs" (e.g., AWS). What is the difference between them (to you), and do you envision this project being more of one, or more of the other as it matures?
> 
> This project is intended to interface with the majority of our public facing
> APIs from code. We also wanted to avoid confusion with some of the other New
> Relic Projects, like the Go Agent.
> 
> An SDK in my mind would help developers write modules, or plugins, or some
> other discrete and well-defined package. An SDK might also include tools to
> create a new project, lint a project, help developers conform to newer patterns
> etc.
> 
> From that perspective, I think the term client here makes sense. With this
> project, we provide a collection of packages with methods that allow users to
> operate the New Relic APIs. What the end-user code looks like, or how it
> behaves is entirely out of scope here from my perspective.

OK, that sounds like a _client_ to me as well. Mostly a low-level client interface with few (if any) abstractions on top. Understanding the intended scope will help me figure out (a) what to expect over the longer term, and (b) what kinds of things I should think about contributing back vs vending as a separate package.

> > Are you able to discuss anything around the conditions under which this project would graduate from a Community Project to a Community Plus Project? (Which gains: “Support requests can be made through Github, Community, and Ticketed Support channels, depending on the service level associated with the New Relic account.”)
> 
> It sounds like a matter of committing a small team to a customer SLA. I don't
> know what the future holds on this point. Is there anything in particular
> you're looking for here?

Frankly, it's being able to use my super-duper, ultra-platinum, really expensive support package to help me work through issues _faster_. I'd like to be able to open a support ticket and have them be more prepared to help me when I'm trying to track down an issue that's happening between the client and the API. This weekend we ran into issues, and the first thing out of their mouth was "we don't support that".

I've worked on the front-lines of developer tooling at infrastructure-related companies before, working directly with customers about their issues using our open-source software. I understand that a balance has to be struck with regard to resources and availability, etc. New Relic, Inc. seems to have a documented set of support tiers and their descriptions (which I appreciate). But knowing my own needs, I'm wondering if there are plans to keep this project's formal support where it is, or if there are plans to move it up a notch along with shipping a 1.0.0.

I'm not asking for a definitive answer beyond what you've already given me — thank you, by the way — but I wanted to submit this as enterprise customer feedback into whatever that discussion looks like. These are things that _I'm_ thinking about as I interact with the products, services, and code from New Relic, Inc.

Thanks!

**Comment by zlesnr** [comment]
> > We can discuss a 1.x as a team and see what the right course of 
> > action is. Is
> > there a concern with the version being pre 1.x that you are able to 
> > share?
> 
> Only that, in terms of semantic versioning, pre-1.0.0 simply means 
> that there is no discernible software contract in-place yet. This 
> means that the code I write today may not work tomorrow (more or 
> less). As you explain yourself, you do it "to remain nimble" which I 
> understand as a developer, but the counter-argument is that the 
> _nimbleness_ for you comes at the cost of _reliability_ for me.

Just keep in mind that a 1.x doesn't mean we won't break things.  It 
just means that we'll communicate through the release of a 2.x that we 
have done so, which I think you would find acceptable given your 
interpretation on semver (which also seems to align with ours).

> On behalf of enterprise customers, I look forward to a stable and 
> supported 1.0.0 release (meaning that I get to use my super-duper, 
> ultra-platinum, really expensive support package for this project) 
> where backwards-compatibility guarantees are a thing, and there are 
> other bits of software contract that I can rely on.

Understood.  Note that if you use our other projects, you are already 
likely relying on this project, though perhaps not directly which is 
probably more of your concern.

> > > Do you intend to adopt semantic versioning as a software contract, 
> > > and if so, which things are in/out-of-bounds? (e.g., versions of 
> > > Go, versions of TLS, TLS ciphers, will they apply to the whole 
> > > repo or by-package?)
> > 
> > 
> > We currently adhere to semantic version for all of our releases and 
> > we
> > release the client as a single "atomic" release. The version bumps 
> > reflect
> > change since the prior release.
> > With regard to TLS support, I would expect that services would 
> > constrain the
> > TLS support far more than this project.
> > I'm seeing posts like this, for example.
> > https://discuss.newrelic.com/t/january-tls-updates-apis-and-browser-apm/88869
> > For Go versions, probably v1.13+ is a reasonable constraint.
> > #474 to follow up.
> 
> It's great to hear that the project views itself as being 
> semantically-versioned… but that's not written down in any obvious 
> places (e.g., README), and the reality is that most software project 
> still have not adopted semver, so I (as a consumer) can't _assume_ 
> such a thing.

Understood.  I would caution you against making any assumptions of 
stability based solely on a version number.  Many projects operate for 
years without ever releasing a 1.x  Take Terraform for the nearest 
example.

> But semantic versioning only addresses backwards-compatibility — and 
> even then, only addresses the compatibility of some parts and not 
> others. It's not a silver bullet. If, in the future, all New Relic 
> endpoints suddenly expected TLS 1.3 or HTTP/3 or something else that 
> doesn't impact function signatures, are they in-scope, or out of scope 
> for the client API? Do you bump major version, minor version, or patch 
> for such a change?

This may not be a great example since I don't think we would suddenly 
make changes that would affect the wide spread of agent versions in very 
tricky places spread globally, and certainly without notice and 
coordination.  But to follow the train of thought here, as long as the 
underlying Go packages supported the protocols required, then there 
should be no impact to users of this project.  If there were a code 
change required for us to support a new protocol, then we would version 
the release according to the significance of the change.  I think that's 
pretty standard practice.  Said another way, if there isn't a code 
change required for this project to support the protocols in question, 
then there isn't something to release.

> > It sounds like a matter of committing a small team to a customer 
> > SLA. I don't
> > know what the future holds on this point. Is there anything in 
> > particular
> > you're looking for here?
> 
> Frankly, it's being able to use my super-duper, ultra-platinum, really 
> expensive support package to help me work through issues _faster_. I'd 
> like to be able to open a support ticket and have them be more 
> prepared to help me when I'm trying to track down an issue that's 
> happening between the client and the API. This weekend we ran into 
> issues, and the first thing out of their mouth was "we don't support 
> that".

If you're having issues with the client and API, please file any bugs 
you find the associated project. We'll mention your scenario to the 
proper parties to help prevent these sorts of interactions in the 
future.

> I've worked on the front-lines of developer tooling at 
> infrastructure-related companies before, working directly with 
> customers about their issues using our open-source software. I 
> understand that a balance has to be struck with regard to resources 
> and availability, etc. New Relic, Inc. seems to have a documented set 
> of support tiers and their descriptions (which I appreciate). But 
> knowing my own needs, I'm wondering if there are plans to keep this 
> project's formal support where it is, or if there are plans to move it 
> up a notch along with shipping a 1.0.0.

We have no plans to raise the support tier of our projects at this time.  
As for a 1.x, this project is less than a year old, and so I think we've 
got a few months before we figure out what a 1.x means for us.

I'll close this out, but hopefully I've answered your questions and 
clarified the purpose of this project.  As always, let us know if you 
have any other questions.

Cheers

**Comment by skyzyx** [comment]
> Just keep in mind that a 1.x doesn't mean we won't break things. It just means that we'll communicate through the release of a 2.x that we have done so, which I think you would find acceptable given your interpretation on semver (which also seems to align with ours).

Understood. A major version bump signals backwards-incompatible changes.

> Understood. I would caution you against making any assumptions of stability based solely on a version number. Many projects operate for years without ever releasing a 1.x Take Terraform for the nearest example.

That's correct. Again, semantic versioning is not a silver bullet. But Terraform also signals backwards-compatibility guarantees in _other_ ways. They treat the minor as the major at this stage of their development.


> > But semantic versioning only addresses backwards-compatibility — and even then, only addresses the compatibility of some parts and not others. It's not a silver bullet. If, in the future, all New Relic endpoints suddenly expected TLS 1.3 or HTTP/3 or something else that doesn't impact function signatures, are they in-scope, or out of scope for the client API? Do you bump major version, minor version, or patch for such a change?
> 
> This may not be a great example since I don't think we would suddenly make changes that would affect the wide spread of agent versions in very tricky places spread globally, and certainly without notice and coordination. But to follow the train of thought here, as long as the underlying Go packages supported the protocols required, then there should be no impact to users of this project. If there were a code change required for us to support a new protocol, then we would version the release according to the significance of the change. I think that's pretty standard practice. Said another way, if there isn't a code change required for this project to support the protocols in question, then there isn't something to release.

Makes sense. Different organizations reason about this differently, so understanding how New Relic reasons about these types of things is valuable to understand.

> If you're having issues with the client and API, please file any bugs you find the associated project. We'll mention your scenario to the proper parties to help prevent these sorts of interactions in the future.

I know, and I do. 😄

But sometimes there's a need to work with this group _as well as_ official New Relic support, and there are times when the customer ends up having to be the go-between. While I'm not looking to place blame, I think it needs to be acknowledged that this happens sometimes, and I'd be interested in seeing if this is something that can be smoothed-out.

> > But knowing my own needs, I'm wondering if there are plans to keep this project's formal support where it is, or if there are plans to move it up a notch along with shipping a 1.0.0.
> 
> We have no plans to raise the support tier of our projects at this time. As for a 1.x, this project is less than a year old, and so I think we've got a few months before we figure out what a 1.x means for us.

Appreciate the honesty here. Thank you.

> I'll close this out, but hopefully I've answered your questions and clarified the purpose of this project. As always, let us know if you have any other questions.

Certainly. Thank you again.
